version: '3.1'

services:
         

    nginx:
        image: streamlit
        ports:
            - 8051:8051
        deploy:
            replicas: 2
networks: 
  default: 
    external: 
      name: webapp-network 


