---
- hosts: all
  become: false

  tasks:
      - name: Stop running container
        command: sudo docker stop devops_project
        ignore_errors: yes

      - name: Remove running container
        command: sudo docker rm  devops_project
        ignore_errors: yes

      - name: Build new image
        command: sudo docker build -t 1365890/devops_projects -f  /home/jenkins/Devops-project/Dockerfile .
        ignore_errors: yes

      - name: create a container with the devops-project  image
        command: sudo docker run -d --name devops_project -p 8080:8080 1365890/devops_projects:latest


      

     
      

